# Generated by Django 3.0.5 on 2021-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=12)),
            ],
        ),
    ]
