# Generated by Django 3.0.5 on 2021-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Client',
        ),
    ]
